### ISSUE TITLE
CI/CD 스크립트 작성  🔥 🔥

### ISSUE THREAD

**Issue by gracia10** [LuxuryBrands/LuxuryBrands_Airflow#1]
---
name: feat
about: feat issue template
title:  CI/CD 스크립트 작성
labels: feat
assignees: '임형우'
---

### Airflow CI

- Trigger
  - pull_request
    - "main"
    - "develop"
- Jobs
  - flake8
  - unittest

### Airflow CD

- ..

## Example code
```python
가능한 경우 여기에 몇 가지 예제 코드를 입력해주세요.
```

## Error log

```
에러 로그가 있다면 여기에 입력해주세요.
```

**Comment by Hyuoo** [comment]
ETL작업 완료 후 EMR 커넥션 체크

**Comment by Hyuoo** [comment]
ELT작업 완료 후 Redshift 커넥션 체크
